require './main.jade'
require "/imports/ui/layout/layout.jade"
require "/imports/ui/navbar/navbar.jade"
require "/imports/ui/footer/footer.jade"
require "/imports/ui/access-denied/access-denied.jade"
require "/imports/ui/help/help.jade"
require "/imports/ui/info/info.jade"
require "/imports/ui/settings/settings.jade"

require "/imports/api/methods.coffee"
require "/imports/ui/router.coffee"
require "/imports/ui/listSurveys/listSurveys.coffee"
require "/imports/ui/editSurvey/editSurvey.coffee"
require "/imports/ui/viewSurvey/viewSurvey.coffee"
require "/imports/ui/chart/chart.coffee"